test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: s3
  access_key_id: <%= ENV['AWS_S3_ACCESS_KEY_ID']%>
  secret_access_key: <%= ENV['AWS_S3_SECRET_ACCESS_KEY']%>
  region: 'us-west-1'
  bucket: <%= ENV['AWS_S3_BUCKET']%>
